function scenario = Intersection_Scenario_1()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.6 and Automated Driving Toolbox 2.0.
% Generated on: 22-Aug-2019 14:31:47

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [35 0 0;
    -35 0 0];marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('DoubleSolid')
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(6, 'Width', 4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification);

roadCenters = [0 35 0;
    0 -35 0];marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('DoubleSolid')
    laneMarking('Dashed')
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(6, 'Width', 4, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification);

